
export const SET_CURRENT_USER_TYPE = 'SET_CURRENT_USER_TYPE'

export const SET_CURRENT_USER_DETAIL = 'SET_CURRENT_USER_DETAIL'

export const GET_USER_DETAIL = 'GET_USER_DETAIL'
export const GET_USER_DETAIL_LOADING = 'GET_USER_DETAIL_LOADING'
export const GET_USER_DETAIL_SUCCESS = 'GET_USER_DETAIL_SUCCESS'
export const GET_USER_DETAIL_ERROR = 'GET_USER_DETAIL_ERROR'

export const GET_ALL_JOB_LIST = 'GET_ALL_JOB_LIST';
export const GET_ALL_JOB_LIST_LOADING = 'GET_ALL_JOB_LIST_LOADING';
export const GET_ALL_JOB_LIST_SUCCESS = 'GET_ALL_JOB_LIST_SUCCESS';
export const GET_ALL_JOB_LIST_ERROR = 'GET_ALL_JOB_LIST_ERROR';


export const LOG_OUT = 'LOGOUT'
