
export const SET_CURRENT_USER_TYPE = 'SET_CURRENT_USER_TYPE'

export const SET_CURRENT_USER_DETAIL = 'SET_CURRENT_USER_DETAIL'

export const GET_USER_DETAIL = 'GET_USER_DETAIL'
export const GET_USER_DETAIL_LOADING = 'GET_USER_DETAIL_LOADING'
export const GET_USER_DETAIL_SUCCESS = 'GET_USER_DETAIL_SUCCESS'
export const GET_USER_DETAIL_ERROR = 'GET_USER_DETAIL_ERROR'

export const LOG_OUT = 'LOGOUT'
